apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  labels:
    app: kafka_producer
spec:
  selector:
    app: kafka_producer
  ports:
    - protocol: TCP
      port: 80               
      targetPort: 8084        
      nodePort: 30004        
  type: NodePort              